[package]
name = "smart_pointers"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'

[features]
default = []
alloc = []


[dependencies]
heapless = "0.7.16"
libc = { version = "0.2.147", default-features = false }
rand = "0.8.5"
